import os
import subprocess
import csv
from datetime import datetime
from typing import Optional

class JMeterConfig:
    """Configuration holder for the test environment."""
    def __init__(self, 
                 target_host: str = "localhost", 
                 target_port: int = 8080,
                 jmeter_path: str = "jmeter", 
                 threads: int = 5, 
                 loops: int = 10,
                 output_dir: str = "./jmeter_results"):
        self.target_host = target_host
        self.target_port = target_port
        self.jmeter_path = jmeter_path
        self.threads = threads
        self.loops = loops
        self.output_dir = output_dir
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        self.jmx_file = os.path.join(output_dir, f"test_plan_{self.timestamp}.jmx")
        self.jtl_file = os.path.join(output_dir, f"results_{self.timestamp}.jtl")
        self.report_dir = os.path.join(output_dir, f"report_{self.timestamp}")

class JMeterTestPlanBuilder:
    """Responsible for generating the JMeter XML (.jmx) file."""
    
    def __init__(self, config: JMeterConfig):
        self.config = config

    def generate(self) -> str:
        host = self.config.target_host
        port = self.config.target_port
        threads = self.config.threads
        loops = self.config.loops
        
        xml_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.3">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Mock App Load Test" enabled="true">
      <stringProp name="TestPlan.comments">Generated by Python OOP Script</stringProp>
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" enabled="true">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
      <stringProp name="TestPlan.user_define_classpath"></stringProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Thread Group" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <stringProp name="LoopController.loops">{loops}</stringProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">{threads}</stringProp>
        <stringProp name="ThreadGroup.ramp_time">1</stringProp>
        <longProp name="ThreadGroup.start_time">1620000000000</longProp>
        <longProp name="ThreadGroup.end_time">1620000000000</longProp>
        <boolProp name="ThreadGroup.scheduler">false</boolProp>
        <stringProp name="ThreadGroup.duration">0</stringProp>
        <stringProp name="ThreadGroup.delay">0</stringProp>
        <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
      </ThreadGroup>
      <hashTree>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="GET /" enabled="true">
          <stringProp name="HTTPSampler.domain">{host}</stringProp>
          <stringProp name="HTTPSampler.port">{port}</stringProp>
          <stringProp name="HTTPSampler.path">/</stringProp>
          <stringProp name="HTTPSampler.method">GET</stringProp>
        </HTTPSamplerProxy>
        <hashTree/>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="GET /items" enabled="true">
          <stringProp name="HTTPSampler.domain">{host}</stringProp>
          <stringProp name="HTTPSampler.port">{port}</stringProp>
          <stringProp name="HTTPSampler.path">/items</stringProp>
          <stringProp name="HTTPSampler.method">GET</stringProp>
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" enabled="true">
            <collectionProp name="Arguments.arguments">
              <elementProp name="id" elementType="HTTPArgument">
                <boolProp name="HTTPArgument.always_encode">false</boolProp>
                <stringProp name="Argument.name">id</stringProp>
                <stringProp name="Argument.value">1</stringProp>
                <stringProp name="Argument.metadata">=</stringProp>
              </elementProp>
            </collectionProp>
          </elementProp>
        </HTTPSamplerProxy>
        <hashTree/>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="POST /orders" enabled="true">
          <stringProp name="HTTPSampler.domain">{host}</stringProp>
          <stringProp name="HTTPSampler.port">{port}</stringProp>
          <stringProp name="HTTPSampler.path">/orders</stringProp>
          <stringProp name="HTTPSampler.method">POST</stringProp>
          <boolProp name="HTTPSampler.postBodyRaw">true</boolProp>
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" enabled="true">
            <collectionProp name="Arguments.arguments">
              <elementProp name="" elementType="HTTPArgument">
                <boolProp name="HTTPArgument.always_encode">false</boolProp>
                <stringProp name="Argument.name"/>
                <stringProp name="Argument.value">{{"item_id": 1, "quantity": 1}}</stringProp>
                <stringProp name="Argument.metadata">=</stringProp>
              </elementProp>
            </collectionProp>
          </elementProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
        </HTTPSamplerProxy>
        <hashTree>
          <HeaderManager guiclass="HeaderPanel" testclass="HeaderManager" testname="HTTP Header Manager" enabled="true">
            <collectionProp name="HeaderManager.headers">
              <elementProp name="" elementType="Header">
                <stringProp name="Header.name">Content-Type</stringProp>
                <stringProp name="Header.value">application/json</stringProp>
              </elementProp>
            </collectionProp>
          </HeaderManager>
          <hashTree/>
        </hashTree>
        <ResultCollector guiclass="SummaryReport" testclass="ResultCollector" testname="Summary Report" enabled="true">
          <boolProp name="ResultCollector.error_logging">false</boolProp>
          <stringProp name="filename">{self.config.jtl_file}</stringProp>
        </ResultCollector>
        <hashTree/>
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>"""
        return xml_content
        
    
class LoadTestRunner:
    """Main Orchestrator class to manage the test lifecycle."""
    
    def __init__(self, config: JMeterConfig):
        self.config = config
        self.builder = JMeterTestPlanBuilder(config)
        self._ensure_output_dir()

    def _ensure_output_dir(self):
        if not os.path.exists(self.config.output_dir):
            os.makedirs(self.config.output_dir)
            print(f"[INFO] Created output directory: {self.config.output_dir}")

    def prepare_test_plan(self):
        """Writes the .jmx file to disk."""
        print(f"[INFO] Generating JMeter Test Plan: {self.config.jmx_file}")
        xml_content = self.builder.generate()
        with open(self.config.jmx_file, 'w') as f:
            f.write(xml_content)
        print("[INFO] Test Plan generated successfully.")

    def run_test(self) -> bool:
        """Executes the JMeter CLI command."""
        cmd = [
            self.config.jmeter_path, 
            "-n", 
            "-t", self.config.jmx_file, 
            "-l", self.config.jtl_file
        ]
        
        print(f"[INFO] Running JMeter Command: {' '.join(cmd)}")
        try:
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if result.returncode == 0:
                print("[SUCCESS] JMeter test execution completed.")
                return True
            else:
                print(f"[ERROR] JMeter failed with code {result.returncode}")
                print(f"STDERR: {result.stderr}")
                return False
        except FileNotFoundError:
            print(f"[ERROR] JMeter not found at '{self.config.jmeter_path}'. Ensure it is installed and in PATH.")
            return False
        except Exception as e:
            print(f"[ERROR] Unexpected error: {e}")
            return False

    def summarize_results(self):
        """Parses the .jtl CSV file to provide a simple summary."""
        if not os.path.exists(self.config.jtl_file):
            print("[WARN] Results file not found. Cannot summarize.")
            return

        total = 0
        errors = 0
        avg_time = 0
        
        try:
            with open(self.config.jtl_file, 'r') as f:
                # FIXED: Let DictReader handle the header naturally
                reader = csv.DictReader(f)
                
                for row in reader:
                    total += 1
                    # Check for 'false' string (JMeter CSV uses lowercase)
                    if row.get('success', '').lower() == 'false':
                        errors += 1
                    try:
                        avg_time += int(row.get('elapsed', 0))
                    except (ValueError, TypeError):
                        pass
                
                if total > 0:
                    avg_time = avg_time / total
                    success_rate = ((total - errors) / total) * 100
                    
                    print("\n" + "="*30)
                    print("TEST SUMMARY")
                    print("="*30)
                    print(f"Total Requests: {total}")
                    print(f"Errors:         {errors}")
                    print(f"Success Rate:   {success_rate:.2f}%")
                    print(f"Avg Response:   {avg_time:.2f} ms")
                    print("="*30)
                else:
                    print("[WARN] No samples recorded in results file.")
                    
        except Exception as e:
            print(f"[ERROR] Could not parse results file: {e}")
            import traceback
            traceback.print_exc()

    def execute_full_cycle(self):
        """Convenience method to run the whole flow."""
        self.prepare_test_plan()
        success = self.run_test()
        if success:
            self.summarize_results()
        else:
            print("[ABORT] Skipping summary due to execution failure.")

if __name__ == "__main__":
    config = JMeterConfig(
        target_host="localhost",
        target_port=5000,
        jmeter_path="jmeter",
        threads=10,
        loops=5
    )

    runner = LoadTestRunner(config)
    print(f"Starting Load Test against {config.target_host}:{config.target_port}...")
    runner.execute_full_cycle()
