apiVersion: v1
kind: ServiceAccount
metadata:
  name: oms-service-account
  namespace: oms
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oms-role
  namespace: oms
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oms-role-binding
  namespace: oms
subjects:
  - kind: ServiceAccount
    name: oms-service-account
    namespace: oms
roleRef:
  kind: Role
  name: oms-role
  apiGroup: rbac.authorization.k8s.io
